---
abstract: http://postgre.st/
author:
  - 'Chia-liang Kao <clkao@clkao.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-App-PgREST
no_index:
  directory:
    - inc
    - share
    - t
    - xt
requires:
  DBD::Pg: 0
  DBIx::Connector: 0
  File::ShareDir: 0
  IPC::Run3: 0
  JSON::XS: 0
  Plack: 0
  Router::Resource: 0
  Tie::IxHash: 0
  methods: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
